services:
  appbuilder:
    image: test:latest
    hostname: appbuilder
    volumes:
      - ./build:/app/build:rw
      - ./venv:/app/venv:rw
      - ./:/app:ro
    stdin_open: true
    tty: true
  appbuilder_cuda:
    image: vulkansdk_cuda:latest
    hostname: appbuilder
    volumes:
      - ./build:/app/build:rw
      - ./venv:/app/venv:rw
      - ./:/app:ro
    stdin_open: true
    tty: true
    gpus: all
    runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics