#pragma once

#include <iostream>
#include <memory>
#include <vector>
#include <sstream>
#include <fstream>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <string>
#include <algorithm>
#include <functional>
#include <chrono>
#include <thread>
#include <optional>
#include <variant>
#include <array>